### ISSUE TITLE
Help please compile the project, I can not compile it.

### ISSUE THREAD

**Issue by VitalikObject** [Mimi8298/GL.Servers#6]
I can not compile the project, please help to compile it.

**Comment by LimoneSister** [comment]
Same where is GL.Core.dll? We need it to Compile

**Comment by 955s** [comment]
I can not compile the project, please help to compile it.

**Comment by jakovmarkovanovic** [comment]
Ji

**Comment by NotHuza** [comment]
Hi

**Comment by z0mbieslayer** [comment]
anyone ever figure out how to compile it?

**Comment by natesworks** [comment]
I can not compile the project, please help to compile it.
